## A Credit Scoring Use Case for Loan Approval: Using Distributed Training with Ray and XGBoost and Feast
![](images/feast_ray_xgboost.png)

In [1]:
import sys
sys.path.insert(0, "../")

### Import General Python libs and modules

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import precision_score

from xgboost_ray import RayXGBClassifier, RayParams
import xgboost as xgb

### Import Feast related modules and definitions from feast_repo directories and Ray modules

In [3]:
from feast import FeatureStore
from utils.data_fetcher import DataFetcher
from queries.ray_train_model import CreditRayXGBClassifier

### Create instances of 
 * feature store
 * data fetcher utility class
 * RayXGBoost classifier for distributed training

In [4]:
# Change this path to your location
REPO_PATH = Path("/Users/jules/git-repos/feast_workshops/module_3/feature_repo")
store = FeatureStore(repo_path=REPO_PATH)
fetcher = DataFetcher(store, REPO_PATH)
xgboost_cls = CreditRayXGBClassifier(store, fetcher)

### Train the RayXGBoost classifier for distributed training on localhost using a four cores or processes

In [5]:
%timeit xgboost_cls.train()

/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/sklearn.py:751: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
2021-09-16 13:52:31,834	INFO services.py:1263 -- View the Ray dashboard at http://127.0.0.1:8265
2021-09-16 13:52:34,181	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 13:52:35,348	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 01:52:35 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 01:52:35 PM INFO:@tracker All of 4 nodes getting started
(pid=91049) [13:52:35] task [xgboost.ray]:140547274213168 got new rank 1
(pid=91050)

[0 0 0 ... 0 0 0]


2021-09-16 13:52:39,666	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 13:52:41,108	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 01:52:41 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 01:52:41 PM INFO:@tracker All of 4 nodes getting started
(pid=91058) [13:52:41] task [xgboost.ray]:140660000323184 got new rank 0
(pid=91058) [13:52:41] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=91062) [13:52:41] task [xgboost.ray]:140721875809856 got new rank 2
(pid=91062) [13:52:41] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 13:52:45,907	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 13:52:47,350	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 01:52:47 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 01:52:47 PM INFO:@tracker All of 4 nodes getting started
(pid=91071) [13:52:47] task [xgboost.ray]:140272312387040 got new rank 0
(pid=91071) [13:52:47] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=91072) [13:52:47] task [xgboost.ray]:140603017676400 got new rank 1
(pid=91072) [13:52:47] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 13:52:52,300	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 13:52:53,854	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 01:52:53 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 01:52:53 PM INFO:@tracker All of 4 nodes getting started
(pid=91083) [13:52:53] task [xgboost.ray]:140550110264864 got new rank 0
(pid=91083) [13:52:53] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=91086) [13:52:53] task [xgboost.ray]:140530924877376 got new rank 3
(pid=91086) [13:52:53] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 13:52:58,669	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 13:53:00,534	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 01:53:00 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 01:53:00 PM INFO:@tracker All of 4 nodes getting started
(pid=91095) [13:53:00] task [xgboost.ray]:140641746777568 got new rank 0
(pid=91098) [13:53:00] task [xgboost.ray]:140276154402656 got new rank 3
(pid=91096) [13:53:00] task [xgboost.ray]:140695970678624 got new rank 1
(pid=91097) [13:53:00] task [xgboost.ray]:140240663312224 got new rank 2
(pid=91095) [13:53:00] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=91098) [13:53:00] WARNING: /Users/travis/build/dmlc/xgbo

[0 0 0 ... 0 0 0]


2021-09-16 13:53:05,342	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 13:53:06,905	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 01:53:06 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 01:53:06 PM INFO:@tracker All of 4 nodes getting started
(pid=91123) [13:53:06] task [xgboost.ray]:140448917788128 got new rank 0
(pid=91123) [13:53:06] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=91126) [13:53:06] task [xgboost.ray]:140191949616752 got new rank 3
(pid=91126) [13:53:06] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 13:53:11,911	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 13:53:13,370	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 01:53:13 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 01:53:13 PM INFO:@tracker All of 4 nodes getting started
(pid=91135) [13:53:13] task [xgboost.ray]:140227619026400 got new rank 0
(pid=91135) [13:53:13] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=91138) [13:53:13] task [xgboost.ray]:140712480564800 got new rank 3
(pid=91138) [13:53:13] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 13:53:18,301	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 13:53:19,753	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 01:53:19 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 01:53:19 PM INFO:@tracker All of 4 nodes getting started
(pid=91147) [13:53:19] task [xgboost.ray]:140300112270960 got new rank 0
(pid=91147) [13:53:19] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=91148) [13:53:19] task [xgboost.ray]:140728553137776 got new rank 1
(pid=91148) [13:53:19] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]
6.43 s ± 159 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Define loan requests

In [6]:
loan_requests = [
    {
        "zipcode": [76104],
        "person_age": [22],
        "person_income": [59000],
        "person_home_ownership": ["RENT"],
        "person_emp_length": [123.0],
        "loan_intent": ["PERSONAL"],
        "loan_amnt": [35000],
        "loan_int_rate": [16.02],
        "dob_ssn": ["19530219_5179"]
    },
    {
        "zipcode": [69033],
        "person_age": [66],
        "person_income": [42000],
        "person_home_ownership": ["RENT"],
        "person_emp_length": [2.0],
        "loan_intent": ["MEDICAL"],
        "loan_amnt": [6475],
        "loan_int_rate": [9.99],
        "dob_ssn": ["19960703_3449"]
    }
]

### Predict the loan requests

In [7]:
for loan_request in loan_requests:
    result = round(xgboost_cls.predict(loan_request))
    loan_status = "approved" if result == 1 else "rejected"
    print(f"Loan for {loan_request['zipcode'][0]} code {loan_status}: status_code={result}")

/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/sklearn.py:294: UserWarning: `ray_params` is not `None` and will override the `n_jobs` attribute.
  warnings.warn("`ray_params` is not `None` and will override "
/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/main.py:364: UserWarning: `num_actors` in `ray_params` is smaller than 2 (1). XGBoost will NOT be distributed!
  warnings.warn(
2021-09-16 13:53:32,174	INFO main.py:1476 -- [RayXGBoost] Created 1 remote actors.
2021-09-16 13:53:33,508	INFO main.py:1493 -- [RayXGBoost] Starting XGBoost prediction.


Loan for 76104 code approved: status_code=1


/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/sklearn.py:294: UserWarning: `ray_params` is not `None` and will override the `n_jobs` attribute.
  warnings.warn("`ray_params` is not `None` and will override "
/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/main.py:364: UserWarning: `num_actors` in `ray_params` is smaller than 2 (1). XGBoost will NOT be distributed!
  warnings.warn(
2021-09-16 13:53:33,849	INFO main.py:1476 -- [RayXGBoost] Created 1 remote actors.
2021-09-16 13:53:35,083	INFO main.py:1493 -- [RayXGBoost] Starting XGBoost prediction.


Loan for 69033 code rejected: status_code=0
