## A Credit Scoring Use Case for Loan Approval: Using Distributed Training with Ray and XGBoost and Feast
![](images/feast_ray_xgboost.png)

In [1]:
import sys
sys.path.insert(0, "../")

### Import General Python libs and modules

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import precision_score

from xgboost_ray import RayXGBClassifier, RayParams
import xgboost as xgb

### Import Feast related modules and definitions from feast_repo directories and Ray modules

In [3]:
from feast import FeatureStore
from utils.data_fetcher import DataFetcher
from queries.ray_train_model import CreditRayXGBClassifier

### Create instances of 
 * feature store
 * data fetcher utility class
 * RayXGBoost classifier for distributed training

In [4]:
# Change this path to your location
REPO_PATH = Path("/Users/jules/git-repos/feast_workshops/module_3/feature_repo")
store = FeatureStore(repo_path=REPO_PATH)
fetcher = DataFetcher(store, REPO_PATH)
xgboost_cls = CreditRayXGBClassifier(store, fetcher)

### Train the RayXGBoost classifier for distributed training on localhost using a four cores or processes

In [5]:
%timeit xgboost_cls.train()

/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/sklearn.py:751: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
2021-09-16 07:12:56,045	INFO services.py:1263 -- View the Ray dashboard at http://127.0.0.1:8265
2021-09-16 07:12:58,470	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 07:12:59,849	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 07:12:59 AM INFO:start listen on 10.0.0.233:9091
09/16/2021 07:12:59 AM INFO:@tracker All of 4 nodes getting started
(pid=77791) [07:12:59] task [xgboost.ray]:140217727747408 got new rank 3
(pid=77791)

[0 0 0 ... 0 0 0]


2021-09-16 07:13:04,834	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 07:13:06,383	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 07:13:06 AM INFO:start listen on 10.0.0.233:9091
09/16/2021 07:13:06 AM INFO:@tracker All of 4 nodes getting started
(pid=77797) [07:13:06] task [xgboost.ray]:140400867833312 got new rank 0
(pid=77797) [07:13:06] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=77800) [07:13:06] task [xgboost.ray]:140346719430208 got new rank 3
(pid=77800) [07:13:06] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 07:13:11,354	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 07:13:13,016	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 07:13:13 AM INFO:start listen on 10.0.0.233:9091
09/16/2021 07:13:13 AM INFO:@tracker All of 4 nodes getting started
(pid=77810) [07:13:13] task [xgboost.ray]:140355695187472 got new rank 0
(pid=77810) [07:13:13] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=77813) [07:13:13] task [xgboost.ray]:140462473774944 got new rank 3
(pid=77813) [07:13:13] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 07:13:17,909	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 07:13:19,354	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 07:13:19 AM INFO:start listen on 10.0.0.233:9091
09/16/2021 07:13:19 AM INFO:@tracker All of 4 nodes getting started
(pid=77822) [07:13:19] task [xgboost.ray]:140577456391600 got new rank 0
(pid=77822) [07:13:19] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=77823) [07:13:19] task [xgboost.ray]:140360879404608 got new rank 1
(pid=77823) [07:13:19] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 07:13:24,067	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 07:13:25,520	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 07:13:25 AM INFO:start listen on 10.0.0.233:9091
09/16/2021 07:13:25 AM INFO:@tracker All of 4 nodes getting started
(pid=77833) [07:13:25] task [xgboost.ray]:140438759175648 got new rank 0
(pid=77833) [07:13:25] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=77834) [07:13:25] task [xgboost.ray]:140410473834048 got new rank 1
(pid=77834) [07:13:25] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 07:13:30,455	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 07:13:31,908	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 07:13:31 AM INFO:start listen on 10.0.0.233:9091
09/16/2021 07:13:31 AM INFO:@tracker All of 4 nodes getting started
(pid=77845) [07:13:31] task [xgboost.ray]:140451309700576 got new rank 0
(pid=77848) [07:13:31] task [xgboost.ray]:140682473424448 got new rank 3
(pid=77847) [07:13:31] task [xgboost.ray]:140423970125376 got new rank 2
(pid=77846) [07:13:31] task [xgboost.ray]:140289811117632 got new rank 1
(pid=77845) [07:13:31] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=77848) [07:13:31] WARNING: /Users/travis/build/dmlc/xgbo

[0 0 0 ... 0 0 0]


2021-09-16 07:13:36,972	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 07:13:38,526	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 07:13:38 AM INFO:start listen on 10.0.0.233:9091
09/16/2021 07:13:38 AM INFO:@tracker All of 4 nodes getting started
(pid=77970) [07:13:38] task [xgboost.ray]:140403318474352 got new rank 0
(pid=77970) [07:13:38] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=77971) [07:13:38] task [xgboost.ray]:140714241070656 got new rank 1
(pid=77971) [07:13:38] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 07:13:43,436	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 07:13:44,988	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 07:13:44 AM INFO:start listen on 10.0.0.233:9091
09/16/2021 07:13:45 AM INFO:@tracker All of 4 nodes getting started
(pid=78123) [07:13:45] task [xgboost.ray]:140219187365344 got new rank 0
(pid=78123) [07:13:45] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=78125) [07:13:45] task [xgboost.ray]:140324859823680 got new rank 2
(pid=78125) [07:13:45] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]
6.44 s ± 124 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Define loan requests

In [6]:
loan_requests = [
    {
        "zipcode": [76104],
        "person_age": [22],
        "person_income": [59000],
        "person_home_ownership": ["RENT"],
        "person_emp_length": [123.0],
        "loan_intent": ["PERSONAL"],
        "loan_amnt": [35000],
        "loan_int_rate": [16.02],
        "dob_ssn": ["19530219_5179"]
    },
    {
        "zipcode": [69033],
        "person_age": [66],
        "person_income": [42000],
        "person_home_ownership": ["RENT"],
        "person_emp_length": [2.0],
        "loan_intent": ["MEDICAL"],
        "loan_amnt": [6475],
        "loan_int_rate": [9.99],
        "dob_ssn": ["19960703_3449"]
    }
]

### Predict the loan requests

In [7]:
for loan_request in loan_requests:
    result = round(xgboost_cls.predict(loan_request))
    loan_status = "approved" if result == 1 else "rejected"
    print(f"Loan for {loan_request['zipcode'][0]} code {loan_status}: status_code={result}")

/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/sklearn.py:294: UserWarning: `ray_params` is not `None` and will override the `n_jobs` attribute.
  warnings.warn("`ray_params` is not `None` and will override "
/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/main.py:364: UserWarning: `num_actors` in `ray_params` is smaller than 2 (1). XGBoost will NOT be distributed!
  warnings.warn(
2021-09-16 07:13:49,530	INFO main.py:1476 -- [RayXGBoost] Created 1 remote actors.
2021-09-16 07:13:50,825	INFO main.py:1493 -- [RayXGBoost] Starting XGBoost prediction.


Loan for 76104 code approved: status_code=1


/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/sklearn.py:294: UserWarning: `ray_params` is not `None` and will override the `n_jobs` attribute.
  warnings.warn("`ray_params` is not `None` and will override "
/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/main.py:364: UserWarning: `num_actors` in `ray_params` is smaller than 2 (1). XGBoost will NOT be distributed!
  warnings.warn(
2021-09-16 07:13:51,148	INFO main.py:1476 -- [RayXGBoost] Created 1 remote actors.
2021-09-16 07:13:52,399	INFO main.py:1493 -- [RayXGBoost] Starting XGBoost prediction.


Loan for 69033 code rejected: status_code=0
