## A Credit Scoring Use Case for Loan Approval: Using Distributed Training with Ray and XGBoost and Feast
![](images/feast_ray_xgboost.png)

In [4]:
import sys
sys.path.insert(0, "../")

### Import General Python libs and modules

In [5]:
import pandas as pd
import numpy as np
from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import precision_score

from xgboost_ray import RayXGBClassifier, RayParams
import xgboost as xgb

### Import Feast related modules and definitions from feast_repo directories and Ray modules

In [6]:
from feast import FeatureStore
from utils.data_fetcher import DataFetcher
from queries.ray_train_model import CreditRayXGBClassifier

### Create instances of 
 * feature store
 * data fetcher utility class
 * RayXGBoost classifier for distributed training

In [7]:
# Change this path to your location
REPO_PATH = Path("/Users/jules/git-repos/feast_workshops/module_3/feature_repo")
store = FeatureStore(repo_path=REPO_PATH)
fetcher = DataFetcher(store, REPO_PATH)
xgboost_cls = CreditRayXGBClassifier(store, fetcher)

### Train the RayXGBoost classifier for distributed training on localhost using a four cores or processes

In [8]:
%timeit xgboost_cls.train()

/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/sklearn.py:751: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
2021-09-16 14:39:50,994	INFO services.py:1263 -- View the Ray dashboard at http://127.0.0.1:8265
2021-09-16 14:39:53,272	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 14:39:54,429	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 02:39:54 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 02:39:54 PM INFO:@tracker All of 4 nodes getting started
(pid=95692) [14:39:54] task [xgboost.ray]:140602412537456 got new rank 3
(pid=95692)

[0 0 0 ... 0 0 0]


2021-09-16 14:39:58,625	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 14:40:00,068	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 02:40:00 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 02:40:00 PM INFO:@tracker All of 4 nodes getting started
(pid=95697) [14:40:00] task [xgboost.ray]:140450010514864 got new rank 0
(pid=95697) [14:40:00] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=95700) [14:40:00] task [xgboost.ray]:140341476554304 got new rank 3
(pid=95700) [14:40:00] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 14:40:04,652	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 14:40:06,107	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 02:40:06 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 02:40:06 PM INFO:@tracker All of 4 nodes getting started
(pid=95709) [14:40:06] task [xgboost.ray]:140703470061024 got new rank 0
(pid=95709) [14:40:06] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=95711) [14:40:06] task [xgboost.ray]:140478589453888 got new rank 2
(pid=95711) [14:40:06] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 14:40:10,738	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 14:40:12,185	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 02:40:12 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 02:40:12 PM INFO:@tracker All of 4 nodes getting started
(pid=95720) [14:40:12] task [xgboost.ray]:140459201164288 got new rank 0
(pid=95720) [14:40:12] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=95722) [14:40:12] task [xgboost.ray]:140638207829568 got new rank 2
(pid=95722) [14:40:12] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 14:40:16,948	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 14:40:18,489	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 02:40:18 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 02:40:18 PM INFO:@tracker All of 4 nodes getting started
(pid=95732) [14:40:18] task [xgboost.ray]:140624626677216 got new rank 0
(pid=95732) [14:40:18] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=95733) [14:40:18] task [xgboost.ray]:140506102928960 got new rank 1
(pid=95733) [14:40:18] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 14:40:23,628	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 14:40:25,083	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 02:40:25 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 02:40:25 PM INFO:@tracker All of 4 nodes getting started
(pid=95744) [14:40:25] task [xgboost.ray]:140236702746080 got new rank 0
(pid=95744) [14:40:25] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=95746) [14:40:25] task [xgboost.ray]:140617175451200 got new rank 2
(pid=95746) [14:40:25] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]


2021-09-16 14:40:30,013	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 14:40:31,569	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 02:40:31 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 02:40:31 PM INFO:@tracker All of 4 nodes getting started
(pid=95755) [14:40:31] task [xgboost.ray]:140453028168992 got new rank 0
(pid=95756) [14:40:31] task [xgboost.ray]:140542006224496 got new rank 1
(pid=95757) [14:40:31] task [xgboost.ray]:140298217551424 got new rank 2
(pid=95758) [14:40:31] task [xgboost.ray]:140309609281088 got new rank 3
(pid=95755) [14:40:31] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=95756) [14:40:31] WARNING: /Users/travis/build/dmlc/xgbo

[0 0 0 ... 0 0 0]


2021-09-16 14:40:36,495	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
2021-09-16 14:40:37,947	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
09/16/2021 02:40:37 PM INFO:start listen on 10.0.0.233:9091
09/16/2021 02:40:37 PM INFO:@tracker All of 4 nodes getting started
(pid=95767) [14:40:37] task [xgboost.ray]:140335899231664 got new rank 0
(pid=95767) [14:40:37] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
(pid=95768) [14:40:37] task [xgboost.ray]:140657719731968 got new rank 1
(pid=95768) [14:40:37] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'erro

[0 0 0 ... 0 0 0]
6.29 s ± 236 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Define loan requests

In [9]:
loan_requests = [
    {
        "zipcode": [76104],
        "person_age": [22],
        "person_income": [59000],
        "person_home_ownership": ["RENT"],
        "person_emp_length": [123.0],
        "loan_intent": ["PERSONAL"],
        "loan_amnt": [35000],
        "loan_int_rate": [16.02],
        "dob_ssn": ["19530219_5179"]
    },
    {
        "zipcode": [69033],
        "person_age": [66],
        "person_income": [42000],
        "person_home_ownership": ["RENT"],
        "person_emp_length": [2.0],
        "loan_intent": ["MEDICAL"],
        "loan_amnt": [6475],
        "loan_int_rate": [9.99],
        "dob_ssn": ["19960703_3449"]
    }
]

### Predict the loan requests

In [10]:
for loan_request in loan_requests:
    result = round(xgboost_cls.predict(loan_request))
    loan_status = "approved" if result == 1 else "rejected"
    print(f"Loan for {loan_request['zipcode'][0]} code {loan_status}: status_code={result}")

/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/sklearn.py:294: UserWarning: `ray_params` is not `None` and will override the `n_jobs` attribute.
  warnings.warn("`ray_params` is not `None` and will override "
/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/main.py:364: UserWarning: `num_actors` in `ray_params` is smaller than 2 (1). XGBoost will NOT be distributed!
  warnings.warn(
2021-09-16 14:40:50,269	INFO main.py:1476 -- [RayXGBoost] Created 1 remote actors.
2021-09-16 14:40:51,600	INFO main.py:1493 -- [RayXGBoost] Starting XGBoost prediction.


Loan for 76104 code approved: status_code=1


/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/sklearn.py:294: UserWarning: `ray_params` is not `None` and will override the `n_jobs` attribute.
  warnings.warn("`ray_params` is not `None` and will override "
/Users/jules/miniconda3/lib/python3.9/site-packages/xgboost_ray/main.py:364: UserWarning: `num_actors` in `ray_params` is smaller than 2 (1). XGBoost will NOT be distributed!
  warnings.warn(
2021-09-16 14:40:51,914	INFO main.py:1476 -- [RayXGBoost] Created 1 remote actors.
2021-09-16 14:40:53,244	INFO main.py:1493 -- [RayXGBoost] Starting XGBoost prediction.


Loan for 69033 code rejected: status_code=0
